### ISSUE TITLE
Consider changing policy agreement wording

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#1066]
mySociety have changed the way they word policies on TWFY: https://www.mysociety.org/2015/08/03/how-far-does-your-mp-tread-the-party-line/

My first thoughts are that it's a good change so maybe we should do it too?

**Comment by equivalentideas** [comment]
I like the concept behind their change to series or time based words:

> However, we received a steady stream of emails, tweets and Facebook messages asking how an MP can vote ‘strongly’ or ‘moderately’ for something. To a fly-by reader, it seemed nonsensical, because of course they were thinking of that fact that MPs vote for or against a single motion.

> To counteract this, we’ve used words which we hope encapsulate the concept of a series of votes over time – words like ‘consistently’, ‘occasionally’ and ‘never’.

I do think that 'moderately' is a confusing term here. I think this would be a good thing to do some testing on. As they describe they had to take it out into the world and ask people to rank words because they couldn't agree.

My initial thought was that ['consistently' and 'almost always'](http://www.theyworkforyou.com/mp/24878/nigel_adams/selby_and_ainsty/votes) are too close which confused me. I also think 'generally' feels wrong for us.

I bet if we go through a similar process and do the research in our own context we'll come up with something that's clearer for people using They Vote For You.

**Comment by mlandauer** [comment]
In #1278 @mackaymackay suggested the wording:
* almost always votes in favour
* mostly votes in favour
* sometimes votes in favour
* votes both ways
* sometimes votes against
* mostly votes against
* almost always votes against

**Comment by mlandauer** [comment]
In https://github.com/openaustralia/publicwhip/issues/1278#issuecomment-968407677 I explain why I've fallen firmly now on the side of changing the policy agreement summary wording. A journalist got something pretty fundamental wrong probably because we used the word "strong" in two very different ways which is confusing.

**Comment by mlandauer** [comment]
For reference the complete list of wording that is currently being used in the UK by TheyWorkForYou (see https://github.com/mysociety/theyworkforyou/blob/f792da7fde5e527839cd04ee6ddd5aff7db0ab72/www/includes/utility.php#L1118)

* consistently voted for
* almost always voted for
* generally voted for
* voted a mixture of for and against
* generally voted against
* almost always voted against
* consistently voted against

(The ranges in percentage agreement still look to be exactly the same as what we're using)

**Comment by mlandauer** [comment]
Looking at the wording that mysociety is using again it's definitely growing on me and making much more sense now. I like the "temporal" aspect of it - that it implies that there are multiple votes and that the person might have voted differently at different times. Also, because "consistently" and "almost always" are very similar and fuzzy concepts it doesn't create a clean line when an policy agreement goes over the threshold. It's more clearly a fuzzy concept. Right now we go from "moderate" to "strong" and "strong" to "very strong" when crossing a threshold which seems a much clearer distinction which is probably not fair and might lead people to the wrong conclusion.

**Comment by mlandauer** [comment]
Thanks @mackaymackay for your suggestions. I think they're really close in spirit to what the mysociety folk came up with. On balance their language has a consistency to it. I think your language largely creates sentences that flow better but in this case I think the brutal consistency of their wording is helpful in the current context.

So, after thinking this through and chatting to @katska we think a good first pass is to adopt the mysociety wording. It's **definitely** better than what we have now.

And we can definitely keep working on it. I hugely appreciate your thinking on this.
