### ISSUE TITLE
Vertical alignment on *MP votes on policy* page

### ISSUE THREAD

**Issue by brtrx** [openaustralia/publicwhip#1095]
The introductory paragraph is a bit out of whack. See screenshot below.

![before](https://cloud.githubusercontent.com/assets/8436356/13959905/444c80ca-f056-11e5-94f7-efca37fe95f1.png)

I haven't found the problem anywhere else.

**Comment by Taz17** [comment]
This issue could be fixed by removing the padding that is applied on to the `col-sm-7` class.

![Alignment screenshot](https://user-images.githubusercontent.com/86769131/145928144-8f2dd5bd-4dce-4a0f-b252-a68441635c2c.png)

The above screenshot shows what it would look like with the left and right padding removed. Keep in mind this aligns the paragraph with the grey horizontal line beneath the work Division

The `col-sm-7` class seems to be coming from bootstrap

A hack to fix this issue is to include the following code:

```haml
%p.col-sm-7
  :css
    p.col-sm-7 { padding: 0px 0px }
  How
  = link_to @member.name, @member
  voted compared to someone who believes that
  = link_to @policy.description, @policy
```

instead of

```haml
%p.col-sm-7
  How
  = link_to @member.name, @member
  voted compared to someone who believes that
  = link_to @policy.description, @policy
```

 in `app/views/policies/show_with_member.html.haml`
