### ISSUE TITLE
Cory Bernardi now in Australian Conservatives

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1120]
Bernardi is marked as a rebel for several divisions this week, when he's actually now in the Australian Conservatives (from 7.2.2017).

I've updated the [senators.csv](https://github.com/openaustralia/openaustralia-parser/blob/master/data/senators.csv) file (have created a [pull request](https://github.com/openaustralia/openaustralia-parser/pull/14)).

**Comment by MicaelaMicaela** [comment]
@equivalentideas  @henare  - will this update fix this issue?

**Comment by henare** [comment]
I've just been working out how to do this. It turns out we need to re-parse all the OpenAustralia.org data to incorporate these changes. This is the command I needed to run to update OpenAustralia.org speeches and generate the updated XML with the corrected votes for TVFY:

`cd /srv/www/www.openaustralia.org/current/openaustralia-parser/ && ./parse-speeches.rb 2016.07.01 2017.02.28`

And then to import this into TVFY:

`cd /srv/www/theyvoteforyou.org.au/current/ && /home/deploy/.rvm/wrappers/ruby-2.3.1/ruby bin/rake application:load:divisions[2016-07-01,2017-02-28] application:cache:all RAILS_ENV=production`

I think it's looking OK now. If there's any problems please reopen this or create a new issue.
