### ISSUE TITLE
Divisions not appearing on TVFY (sitting week beginning 20/03/17)

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1130]
The divisions for at least the first half of this sitting week (20/03/17 - 24/03/17) aren't showing up on They Vote For You. 

Only the ones that took place in the House of Representatives yesterday (22/03/17) have appeared.

**Comment by equivalentideas** [comment]
Looks like the issue is that we're missing http://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=269583

From the cron email on the 22nd:

```
./../openaustralia-parser/lib/hansard_parser.rb:223:in `throw': uncaught throw `2017-03-20 senate: Couldn't figure out who Georgiou, P is in division (in a pair)' (NameError)
```

**Comment by equivalentideas** [comment]
I've loaded them into OA

https://github.com/openaustralia/openaustralia-parser/commit/2c3c1055c3c45632961c5985a65f7c7258a71ce0

https://github.com/openaustralia/openaustralia-parser/commit/4cde7c0670e6355caf76c5df8329295600b8c82a

**Comment by equivalentideas** [comment]
Going to follow the instructions here https://github.com/openaustralia/openaustralia/issues/610#issuecomment-248169719 to load the divisions into OA.

**Comment by equivalentideas** [comment]
## Remove HTML cache

> The divisions for at least the first half of this sitting week (20/03/17 - 24/03/17) aren't showing up on They Vote For You.

I'm going to remove the html cache for 2017-03-2*.

```
deploy@kedumba:~$ rm -r /srv/www/www.openaustralia.org/shared/html_cache/2017-03-2*
```

## Re-parse days

I'll re-parse from the 17th on.

```
deploy@kedumba:/srv/www/www.openaustralia.org/current/openaustralia-parser$ cd /srv/www/www.openaustralia.org/current/openaustralia-parser/ && ./parse-speeches.rb 2017.03.20 2017.03.24
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
WARNING: Nokogiri was built against LibXML version 2.7.6, but has dynamically loaded 2.7.8
parse-speeche: 100% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:02:34
db loading  2017-03-20
updating hansard object uk.org.publicwhip/debate/2017-03-20.32.3, changing: at 9 value #00:00:00# to # (Mayo) (13:30):#.
db loading  2017-03-21
db loading  2017-03-22
db loading  2017-03-23
db loading  2017-03-20
db loading  2017-03-21
db loading  2017-03-22
db loading  2017-03-23
```

## Update index

deploy@kedumba:/srv/www/www.openaustralia.org/current/openaustralia-parser$ ../twfy/search/index.pl /srv/www/www.openaustralia.org/shared/searchdb sincefile /srv/www/www.openaustralia.org/shared/searchdb/../s
earchdb-lastupdated
xapian indexing debate 2017-03-20
xapian indexing lords 2017-03-20
xapian indexing debate 2017-03-21
xapian indexing lords 2017-03-21
xapian indexing debate 2017-03-22
xapian indexing lords 2017-03-22
xapian indexing debate 2017-03-23
xapian indexing lords 2017-03-23


## emails

Because this was all really recent, I'm going to let the email alerts go out for these days.

## Reload TVFY

First, reload members:

```
deploy@kedumba:~$ cd /srv/www/theyvoteforyou.org.au/current/ && /home/deploy/.rvm/wrappers/ruby-2.3.1/ruby bin/rake application:load:members RAILS_ENV=production
```

Then load the divisions and update the caches (Updating policy distance cache takes a long long time):

```
deploy@kedumba:~$ cd /srv/www/theyvoteforyou.org.au/current/ && /home/deploy/.rvm/wrappers/ruby-2.3.1/ruby bin/rake application:load:divisions[2017-03-20,2017-03-30] application:cache:all RAILS_ENV=production
```

**Comment by equivalentideas** [comment]
I've followed those steps and the divisions are loaded :) https://theyvoteforyou.org.au/divisions/senate/2017-03/
