### ISSUE TITLE
2018 divisions not appearing on TVFY

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1175]
With the exception of the House sitting week from 26 Feb - 1 Mar 2018, no division data is being uploaded onto They Vote For You for 2018.

Note this [related issue](https://github.com/openaustralia/publicwhip/issues/1171) ("Missing debates/divisions between 2015-2018 on OA.org & TVFY")

**Comment by MicaelaMicaela** [comment]
@mlandauer  the good news is that most of the divisions are now there! the bad news is that there are still a few days that had divisions that are not showing up:

**Senate**
19 March 2018
20 March 2018
21 March 2018
26 March 2018

As of this morning, 27 March 2018 divisions are still not up for either the House or Senate, but as that was only yesterday, they just might not be up yet.

**Comment by mlandauer** [comment]
@MicaelaMicaela those days didn't load because I hadn't yet applied the updates to the people data when they initially ran. So, I re-ran things on openaustralia.org and theyvoteforyou for the days:
* 19 March 2018
* 20 March 2018
* 21 March 2018
* 26 March 2018
* 27 March 2018
I also needed to do a fix for yesterday's Hansard.

So, things should all be good now and up to date. Thanks so much @MicaelaMicaela for checking through everything.
