### ISSUE TITLE
Can't edit divisions on TVFY

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1187]
Although I can write new division summaries, they won't save. I simply return to the unedited division page.

**Comment by jamezpolley** [comment]
This seems to have been caused by elasticsearch being down.

Now that we've switched to NewRelic infra monitoring, I've been able to set up an Alert that will tell us if this process goes away again. We also now have better monitoring and alerting on disk space which should help prevent the problem that (I assume) originally caused elasticsearch to stop.
