### ISSUE TITLE
TVFY records the speaker as having implicitly voted, in cases where Hansard leaves the vote as being merely implied.

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1194]
In [this division](https://theyvoteforyou.org.au/divisions/representatives/2018-10-17/3), the Speaker Tony Smith is listed as voting 'No' despite [not actually voting](https://www.openaustralia.org.au/debate/?id=2018-10-17.126.1). Luckily, this doesn't change the result of the division - it failed - but may indicate a wider problem.

**Comment by jamezpolley** [comment]
Summary: this only affects the speaker, and ony in cases where there is a standing order which would give the same outcome to the vote with or without the speaker's vote. I don't believe this indicates a wider problem.

Just noting here that this has taken me 4 hours of reading code, standing orders, and hansard to come to a conclusion. Parliamentary math is hard.

----

I'm going to talk about this in two ways: first by analysing the standing orders, and by the record in Hansard, and attempting to determine what Parliamentary procedure considers to have happened in this case. Then I'll look at this programatically to figure out what could be done if we want a different outcome to be recorded.

My overall impression is that it's correct to say that the speaker voted in this case; I believe that their explicit statement that they were not voting is in error.

---

According to the [standing rules as at 4 Dec 2017](https://www.aph.gov.au/About_Parliament/House_of_Representatives/Powers_practice_and_procedure/House_of_Representatives_Standing_Orders), I believe that it is correct to say that the speaker voted no in this case.

The relevant rule is SO 47(c)(ii) which requires that "a suspension motion is moved without notice ... can be carried only by an absolute majority of Members"

SO 2 defines a `absolute majority` as "a majority of the membership of the House
(including the Speaker)." SO 3 grants the speaker "The power to exercise a casting vote". SO 135 provides that "Any reasons given by the Speaker for exercising a casting vote in
accordance with section 40 of the Constitution, must be entered in the
Votes and Proceedings"

When a division on a motion to suspend standing orders results in a tie, it's clear that if the speaker voted with either the ayes or the noes, there would be an absolute majority. The question is whether there is any meaningful difference between the speaker voting with the noes, or simply declaring that the the ayes have failed to achieve an absolute majority.

I had a longer semantic argument written making the case that the only sensible way to resolve this is to consider that the speaker has voted with the noes; but I'm going to delete it and simply point to [this division in hansard](https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;db=CHAMBER;id=chamber%2Fhansardr%2Fb8101fb1-edde-4753-a50e-1709934db485%2F0076;query=Id%3A%22chamber%2Fhansardr%2Fb8101fb1-edde-4753-a50e-1709934db485%2F0000%22). Although this isn't a motion to suspend standing orders, there's no record that the Speaker gave any reasons for their casting vote; only that they made a casting vote.

However, in this particular case, there's a recording of the speaker giving reasons for their actions. That seems to be in line with SO135, ie, recording the reasons giving by the Speaker for exercising their casting vote.

If the speaker had not given a vote, I would argue that there's no reason to record their reasons for this; the SOs only allow for recording the reasons *for* casting a vote. Since the outcomes of not voting, and of voting with the noes, are identical, and since the speaker knows that their decision decides the division, I think it has to be taken that even if the speaker says that they are not voting, they are in fact voting..

In addition, it's worth considering [this division](https://theyvoteforyou.org.au/divisions/representatives/2018-12-04/1) which got 73 Ayes and 72 Noes. However, Hansard shows that "The requirements for an absolute majority not having been satisfied, the motion was not carried." I believe that it can only be the case that "an absolute majority" was not reached in this case if it's considered that the Speaker implicitly voted with the noes. 

------------

Programaticaly, there are a few things we could look at if we wanted to change this behaviour:

- The XML for the division in question does note that an absolute majority was not achieved. 

```
<p class="HPS-DivisionFooter">
The requirements for an absolute majority not having been satisfied, the motion was not carried.
</p>
```
  We don't normally pay any attention to this; but i think it's possible that there's a signal here that the speaker did not vote. However, it's clearly not as simple as that; see the 2018-12-04 example where an absolutely majority was not satisfied *because* the speaker voted.

So I don't think it would be worth the effort required to look out for this formulation, unless it happens more often. Even if we were to look out for it, I think that we should be reporting this as the speaker having voted with the winning group.

- (this code)[https://github.com/openaustralia/openaustralia-parser/blob/8a3a1eb08cd7dc52a302327aca2eea78ee1fd2e4/lib/hansard_division.rb#L28] determines whether a division was carried or not carried. We return true if we see certain phrases that indicate that the motion carried and false if we see certain phrases that indicate that the motion did not carry. In any other case, we return an error. If we were to change this code in order to handle the case where a motion has an outcome despite the speaker not voting, we'd have to change from a boolean true/false to a larger set of values: we'd have to return something like one boolean to indicate whether the motion carried or not, and a second boolean to indicate whether the speaker voted or not.

However, I don't see the point in this, since the speaker's vote can only ever result in the outcome that we already detect (in the openaustralia-parser library at least; it seems that TVFY simply counts votes and sometimes gets the wrong anser)

-  We actually do have [some code](https://github.com/openaustralia/openaustralia-parser/blob/8a3a1eb08cd7dc52a302327aca2eea78ee1fd2e4/lib/hansard_day.rb#L62) to handle days where the speaker's vote should not be added to tied votes. That [currently](https://github.com/openaustralia/openaustralia-parser/blob/8a3a1eb08cd7dc52a302327aca2eea78ee1fd2e4/lib/hansard_day.rb#L26) only applies to one date - 2011-02-22.  This is because of a similar vote on that date (see [page 925)](https://parlinfo.aph.gov.au/parlInfo/download/chamber/hansardr/2011-02-22/toc_pdf/7968-5.pdf;fileType=application%2Fpdf), where there was a motion to suspend standing orders which resulted in a 71-71 tie and this an absolute majority was not satisfied.

However, this applies to an entire day, which happened to appear to give a sensible answer on that day, but may not work on all days.

If we're not going to record the speaker having voted in that case, we should also record the speaker as having not voted later in in 2011, where we have [another example (page 6377)](https://parlinfo.aph.gov.au/parlInfo/download/chamber/hansardr/f40cc0c2-a858-4869-8b51-10e159d65b90/toc_pdf/House%20of%20Representatives_2011_06_16_208_Official.pdf;fileType=application%2Fpdf) where a vote to suspend standing orders received 71 ayes and 70 noes, giving a majority of 1 but not satisfying an *absolute* majority.

If we're going to do anything, it seems that we need to be looking out for cases where a division has a majority of one *but* the outcome mentions that the motionwas not carried.

--- 

Addendum: All the instances I could find of an absolute majority not having been satisfied. This includes cases such as 2011-06-16 in which the vote had a majority of 1 but not an absolute majority.

```
representatives_debates/2013-02-07.xml
7018:              <p class="HPS-DivisionFooter">The requirements for an absolute majority not having been satisfied, the motion was not carried.</p>

representatives_debates/2013-06-20.xml
9730:              <p class="HPS-DivisionFooter">The requirements for an absolute majority not having been satisfied, the motion was not carried.</p>

representatives_debates/2012-06-28.xml
14346:              <p class="HPS-DivisionFooter">The requirements for an absolute majority not having been satisfied, the motion was not carried.</p>

representatives_debates/2011-02-22.xml
4526:<para>The requirements of standing order 47(c)(ii) for an absolute majority having not been satisfied, the motion was not carried.</para>

representatives_debates/2018-05-31.xml
1828:              <p class="HPS-DivisionFooter">The requirements for an absolute majority not having been satisfied, the motion was not carried.</p>

representatives_debates/2010-11-18.xml
4347:<para>The requirements for an absolute majority not having been satisfied, the motion was not carried.</para>

representatives_debates/2011-06-16.xml
5313:                  <span class="HPS-Normal">The requirements of standing order 47(c)(ii) for an absolute majority having not been satisfied, the motion was not carried.</span>
5930:                <span class="HPS-Normal">The requirements of standing order 47(c)(ii) for an absolute majority having not been satisfied, the motion was not carried.</span>

representatives_debates/2018-12-05.xml
3373:              <p class="HPS-DivisionFooter">The requirements for an absolute majority not having been satisfied, the motion was not carried.</p>

representatives_debates/2018-10-17.xml
9013:              <p class="HPS-DivisionFooter">The requirements for an absolute majority not having been satisfied, the motion was not carried.</p>

representatives_debates/2018-12-04.xml
5565:              <p class="HPS-DivisionFooter">The requirements for an absolute majority not having been satisfied, the motion was not carried.</p>

representatives_debates/2012-05-21.xml
9529:              <p class="HPS-DivisionFooter">Question negatived. The requirements for an absolute majority not having been satisfied, the motion was not carried.</p>

representatives_debates/2013-06-05.xml
10867:              <p class="HPS-DivisionFooter">The requirements for an absolute majority not having been satisfied, the motion was not carried.</p>
11314:              <p class="HPS-DivisionFooter">The requirements for an absolute majority not having been satisfied, the motion was not carried.</p>

representatives_debates/2011-06-20.xml
950:                <span class="HPS-Normal">The requirements for an absolute majority not having been satisfied, the motion was not carried.</span>
```

**Comment by jamezpolley** [comment]
Connects to #1196

**Comment by jamezpolley** [comment]
I'm going to close this; as I believe that in this particular case we're correct to say that the speaker *did* vote, despite claiming that they weren't voting. If we decide that this isn't what we want to do we should re-open this.

I do think we have a problem with the cases where a division gets a simple majority but fails to pass because of the absolute majority requirement, but that's being tracked in #1196.
