### ISSUE TITLE
compare your representative's votes vs ANY party line

### ISSUE THREAD

**Issue by katska** [openaustralia/publicwhip#1244]
Someone I met who is actively engaged in their community requested: If I live in an area where the sentiment goes one way on an issue, and the local representative is voting against the majority interest/views, I want to know about that. 
I also may want to compare their voting on an issue I care about in comparison to the party I would have voted for.
So for example if I would have voted Greens or Nationals and the local representative from Labor or Liberals voted with their party in the opposite way to my party of choice. Voters for minor parties directly or indirectly give preferences to the major parties at election time, because there's an idea that they're more closely aligned on issues that matter to them. However this isn't necessarily the case.

So I might care about how they voted in relation to their party, but I also care about how they voted in relation to other parties.

**Comment by katska** [comment]
@mackaymackay ages ago you were advocating for the idea of relating our representatives' votes to their party. Conceptually this was something that TVFY intentionally downplayed in its design, to emphasize the representational nature of the relationship to constituents. I put in this related issue after someone told me they would be interested to see how their local member voted compared to the party they voted for, who are not in power, but whose votes go to the major party in power, as the minor party gives their preferences over to that major party that is supposed to be closer to some of their values. Somehow this broader idea makes more sense to me. It would also be useful for people who have independent representatives. 
Do you think it's useful, and doable?

**Comment by mackaymackay** [comment]
Hi @katska  I agree that having some sort of way to gauge party position would be good, but I think something like this may go too far, as it assume party-homogeneity and wouldn't account for rebellions or purposeful absences within parties (e.g. certain Labor members used to leave the chamber during gay marriage votes, back when Labor didn't support it, because they didn't want to vote against it but also didn't want to rebel). A set party position would lose this nuance and just assume that the alternative representative for an electorate would have conformed and voted X, regardless of their individual identity.

As an alternative, it's [been suggested before](https://github.com/openaustralia/publicwhip/issues/1092) that we add party colours to the policy pages (e.g. adding a band of blue around Liberal members etc). Would there be a way to have this party colour function as an option that isn't automatically there? e.g. the page is presented as it is currently, but there's an option to click on that will add colour. This would allow users to get a visual idea of the party breakdown without assuming that all party members would have voted the same. That is, on many policies, they will see members of the same policy spread over many categories, e.g. from voted 'for and against' to 'very strongly against', depending on individual attendance figures, rebellions and length of time in parliament. This would give a more nuanced idea of voting variation rather than just assuming a singular party position (though I acknowledge that parties do indeed tend to have a singular position most of the time).

**Comment by katska** [comment]
@mackaymackay sorry I wasn't clear in the issue, this request came from someone else outside OAF. I was so focused on getting the details of the request down in the issue I quite forgot to add this piece of information!

**Comment by mlandauer** [comment]
I think we would be better placed by focusing our efforts on adding a feature to compare the voting records of two specific people #1251. That's a much more tangible, concrete thing and is more consistent with our overall approach on TVFY of focusing on how individual politicians vote rather than how their parties vote.

I do think that #1251 will go along way to actually to answering that user's need. So, I'm going to close this issue in favour of #1251
