### ISSUE TITLE
aspect ratio appears incorrect for some MP photos

### ISSUE THREAD

**Issue by xavella** [openaustralia/publicwhip#1276]
aspect ratio appears incorrect for some MP photos
example: https://theyvoteforyou.org.au/people/representatives/higgins/katie_allen

**Comment by mlandauer** [comment]
Related to #1225

**Comment by mlandauer** [comment]
After a little investigating as part of working on #1351 I think I know why this is happening. The source images that we originally scraped from aph.gov.au for openaustralia.org.au are not exactly the same dimensions. If I remember correctly when we started they were and so we were able to make some simplifying assumptions. However now they're not all the same.

We were rescaling the images in such a way that they were never bigger than the desired size but could be a bit smaller. So, I just changed the rescaling method so that we ensure that the final image size is exactly what we want. The downside is that we will be cropping a little off of the original image in some cases. Hopefully it won't be too much. Just looking through the generated images it looks like it should be fine but we won't really know until we see it all in production I think.

We will also need to change the image size in TVFY a little to compensate. The default size will be different by a pixel or so but we might as well get this right while we're working on this.

**Comment by katska** [comment]
Interesting that they're not all the same size now. I wonder how they dealing with it that this is no longer standard, and how they are shown in the official context they're originally used, but a pixel or two shouldn't be a problem no! Looking forward to see how these turn out!
