### ISSUE TITLE
The weighting method is deeply confusing 

### ISSUE THREAD

**Issue by Fuviadark** [openaustralia/publicwhip#1278]
I’m very supportive of a site that brings transparency re. the political voting records of our politicians. However, there is no easy way of understanding your weighting method and how it results in someone being assessed as voting “strongly against” for example. Such a choice of words will suggest zeal or force of emotion to a number of your readers who, like me, will find no supporting information to back such a perceived assertion. The weighting explanation that you provide also explains nothing as to why that weighting was chosen, and why the states/words such as “strongly against” were chosen to associate with those numbers. If you could clearly describe why and how you choose to colour to the recorded fact of a vote for or against, by adding strongly for or against etc, it would make this service more valuable for readers like me.

**Comment by mackaymackay** [comment]
This is a great point @Fuviadark 

What other language could we use? Off the top of my head, I'm thinking:

- almost always votes in favour
- mostly votes in favour
- sometimes votes in favour
- votes both ways
- sometimes votes against
- mostly votes against
- almost always votes against

The language is a bit clunky, but may be better? What do you  think @kat @mlandauer?

**Comment by bdcarr** [comment]
Came here for a similar reason. If there's only been one vote on a particular issue, and a given pollie has voted against it, that shows up as 'Very Strongly Against'.  I think you could resolve this by making the # of votes on an issue more prominent when looking a given pollie's issue summary.

You've also got weakly-related motions apparently being counted for an issue with full strength, for example [this one](https://theyvoteforyou.org.au/people/senate/nsw/andrew_bragg/policies/7). I think this could be resolved by allowing votes to have a 'relevance ranking', maybe?

Those two flaws seem to be resulting in Australian Government representatives choosing to spend their well-paid time smearing your org as "hyper partisan" instead of trying to advance the welfare of their citizens.

https://twitter.com/ajamesbragg/status/1458946878322593792

**Comment by mlandauer** [comment]
Thanks @Fuviadark and @bdcarr for dropping by. I really appreciate you bringing your suggestions here.

This is related to #1066 which is an old (but a good) suggestion to change the wording of the policy agreement summary. I agree that our current wording causes confusion. One of the big points of confusion is that divisions are weighted to be either "normal" votes or "strong" votes. This weighting is then used to figure a percentage agreement with a policy. The weighting only effects the relative importance of the votes within that policy. Then, that percentage is converted to a phrase to make it easier to understand. The confusing bit I think is that the word "strong" can appear in the agreement summary phrase but "strong" in this context means something completely different! 

In https://www.smh.com.au/politics/federal/mps-call-for-partisan-political-transparency-site-to-lose-charity-status-20211108-p5971z.html for instance the journalists at one point write:
"Senator Bragg voted against the motion, which was only a symbolic gesture, but it is nonetheless characterised by They Vote For You as a “very strong vote”.

They made a completely incorrect statement there. The individual vote was *not* a "strong" vote but the overall agreement with the policy *was* "strong".

For me this misunderstanding (intentional or otherwise) is enough to put a nail in the coffin of the current policy agreement wording. I think we should address #1066.

@Fuviadark are you also suggesting we provide further explanation of why the vote weighting is chosen the way it is (5 "normal" votes are equivalent to 1 "strong" vote) or how the percentage agreement ranges are chosen? That's so tricky isn't it? The numbers are picked to be reasonable and fairly intuitive. The agreement summary roughly splits the percentage range into 7 parts that are roughly equal. The ranges at the extreme ends are a bit narrower so that "strong" and "very strong" get used a little less often.

**Comment by mlandauer** [comment]
I think most of what's here is addressed by the changes we made to the wording of policy agreement summary at https://github.com/openaustralia/publicwhip/blob/2a0d45009ed08d369546d53076fe6f007732067b/app/helpers/policy_person_distances_helper.rb#L31 and the introduction of a new category when a person has only voted once on a policy and it wasn't a "substantive" vote where actual law was being changed. The second changes is outlined a blog post https://www.oaf.org.au/2022/01/31/a-new-category-has-been-added-to-your-representatives-voting-records/.

**Comment by Fuviadark** [comment]
@mlandauer I think the changes you’ve made on the “strongly against” issue are good, that seems better. TBH I’m not sure that adding info on how a pollie votes on Divisions is adding value, particularly when that is the only vote recorded and the statement the user gets to see (for eg) is “voted consistently against”. This could be seen as misleading in the case where a person votes once on a Division. It could also be misleading where they vote more than once, for or against, in a Division because voting on a Division is not the same as voting on a policy? It could amount to the same thing, but I would argue the reader/user needs more context to accept the conclusion. 
Thanks very much for all your effort by the way. Minor problems such as these aside, I can still easily look up a politician’s voting record and that is very valuable in my view.
One other thing, there are a number of ‘page not found’ notices from links on the Dave Sharma page: “Voted consistently against increasing trade unions' powers in the workplace. [votes](https://theyvoteforyou.org.au/mp.php?mpid=764&dmp=6) - the “votes” link at the end for example. Thanks once more.
