### ISSUE TITLE
number of contributors wildly wrong on FAQ

### ISSUE THREAD

**Issue by katska** [openaustralia/publicwhip#1324]
https://theyvoteforyou.org.au/help/faq

In this section, at least some of the data are wildy out. I picked this up scanning the FAQ and noticed 'contributors' below clocking up at 14283!!

"What time period does it cover?

They Vote For You’s voting and membership data extends back to 2006. New divisions are added as soon as possible after becoming available. We give no warranty for the data so let us know if you find any factual inaccuracies.

The project contains 950 distinct Representatives and Senators from 31 parties who have voted across 7,377 divisions. In total 627,290 votes were cast, 224 were against the majority vote for their party giving an average rebellion rate of 0.04%.

**14283** contributors have created 280 policies and summarised 3831 divisions. "

**Comment by mlandauer** [comment]
I'm guessing the "contributors" listed are all the registered users rather than the people that have contributed to creating policies or editing policies or divisions. Since we're downplaying the community contributions (see #1280) maybe we should rewrite this bit to remove the number of contributors completely?
