### ISSUE TITLE
House of Rep divisions missing post-midnight 9 Feb 2022

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1333]
We are missing the House of Reps divisions related to the Religious Discrimination bill.

They officially occurred on 9 Feb 2022 (i.e. they are reported in the Hansard for that day), but they actually occurred in the early hours of 10 Feb 2022. This date discrepancy may be why they weren't uploaded.

Note that no other divisions took place in the House of Reps on either the 9th or the 10th, so its just these early-hours ones that are missing.

**Comment by mlandauer** [comment]
Actually looks like the XML file on data.openaustralia.org.au that comes out of the parser was completely messed up for the house of reps on 9 feb 2022. I'm guessing that because the scraper tried to get the XML from aph at 9am roughly, only a few hours after things finished, it's likely that there was a problem with the hansard record at that point.

I've rescraped that data. Seems to be picking up other things now. Now loading it back into TVFY to see if that fixes things.

**Comment by mlandauer** [comment]
They seem to be loaded now. Phew. https://theyvoteforyou.org.au/divisions/representatives/2022-02-09/9

I haven't updated all the caches, so Dave Sharma, for instance is showing still as not having ever rebelled. These will get updated automatically tomorrow.
