### ISSUE TITLE
Free votes on the Mitochondrial Donation bill

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1334]
All the divisions on the Mitochondrial Donation Law Reform (Maeve’s Law) Bill 2021 were free votes (currently they're showing up as rebellions):
- https://theyvoteforyou.org.au/divisions/senate/2022-02-09/5
- https://theyvoteforyou.org.au/divisions/senate/2022-02-09/6
- https://theyvoteforyou.org.au/divisions/senate/2022-02-09/7
- https://theyvoteforyou.org.au/divisions/senate/2022-02-10/6
- https://theyvoteforyou.org.au/divisions/senate/2022-02-10/8
- https://theyvoteforyou.org.au/divisions/senate/2022-02-10/9
- https://theyvoteforyou.org.au/divisions/senate/2022-02-10/10

**Comment by mlandauer** [comment]
Actually I won't assign this to myself until I actually start working on it!

**Comment by mlandauer** [comment]
Noticed that this related division in the house of reps has a large number of rebellions showing as well: https://theyvoteforyou.org.au/divisions/representatives/2021-12-01/3. I found it by googling and coming across this article: https://www.theguardian.com/australia-news/2021/dec/01/controversial-mitochondrial-donation-legalised-after-conscience-vote

I missed this initially because when you go to the divisions page and sort by rebellions https://theyvoteforyou.org.au/divisions/all?sort=rebellions it's actually only showing you divisions in 2022. This I completely missed!

To see 2021 you have to scroll to the bottom of the page https://theyvoteforyou.org.au/divisions/all/2021?sort=rebellions. Then you see 27 rebellions on a single division. Eek!

**Comment by mlandauer** [comment]
Fixed by bcf9bc18f996f2421a6de4311d98a27bc06c56d5

**Comment by mlandauer** [comment]
Deploying this to production now. I probably won't update the caches now. I'll just wait until it happens tomorrow morning
