### ISSUE TITLE
Don't embed content from TVFY on openaustralia.org.au anymore. Send people to TVFY directly

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#1385]
At the moment we embed content from theyvoteforyou.org.au on openaustralia.org.au using the API (or to be precise a legacy XML API).

This looks something like this for Justine Elliot (my local member):
At https://www.openaustralia.org.au/mp/justine_elliot/richmond 
![image](https://user-images.githubusercontent.com/2221/160308672-16b76257-ef27-4fd2-8f84-775533f7c1f0.png)

On theyvoteforyou.org.au at https://theyvoteforyou.org.au/people/representatives/richmond/justine_elliot:
![image](https://user-images.githubusercontent.com/2221/160308725-a5fa7a97-d58d-42d8-803d-a062f9e61389.png)

When when launched TVFY it was obviously unknown and so it made sense to follow what people had done in the UK and embed content from TVFY on openaustralia. However, now what's on openaustralia is a "poor cousin" of what's on TVFY at least in terms of voting. The list of policies isn't automatically kept up to date and we don't have it matching exactly the categories as used on TVFY.

Obviously this is symptomatic of a deeper problem where we're duplicating functionality across two sites.

We're also putting much more effort these days into updating TVFY rather than openaustralia. So given this I think we should direct people from openaustralia.org to TVFY for the voting information rather than embedding.

This will also help create a clearer distinction between the two sites. TVFY is then the place you go for voting and openaustralia.org.au is the place you go for speeches. It's kind of weird but it would be better than what we have right now which is even more confusing.

Another small advantage is if we make this change we can finally remove the legacy XML API. We will still need to support redirects from urls that include the member ID so we can link directly from a member page on OA to the member page on TVFY.

@katska @mackaymackay what do you think? Any reasons that I've missed for keeping things as they currently are?

**Comment by katska** [comment]
@mlandauer @mackaymackay agreed. That's bad to have out of date voting positions on openaustralia.org.au especially if it's not clear the information is only updated periodically. 

Just to be clear @mlandauer the current situation is that we don't have the resources to improve or develop openaustralia.org.au and that we don't want to show out of date info. So it's better to remove it for now and point to they their specific voting record over at they vote for you, as you suggest. 

We could include something as simple as ""See how they vote" but that loses the connection to issues. 

Are there clear key issues of importance that could be listed, so that links can go straight to them at they vote for you? 

...
The thinking behind this suggestion is that what feels lost here is the immediacy of being able to read their positions in context, are there easy ways to help bridge that gap, either in the wording or what's presented on the page, a link to a series of person/policy pages for example? These don't need to be updated because they don't contain the position, but they seed the interest based on connection to issues.

**Comment by mackaymackay** [comment]
@mlandauer  I agree with your reasoning and can't think of anything to add.

**Comment by mlandauer** [comment]
That's done now. This is what it looks like now
![image](https://user-images.githubusercontent.com/2221/162109794-bd5a3962-9528-40f2-b88c-285429205981.png)

It's pretty rubbish but at least **something** is there now
