### ISSUE TITLE
Add more context to history page

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#845]
Another one from @erietta

> https://theyvoteforyou.org.au/history page may need more context e.g. what are edits, how to make edits, perhaps a call to action to join. Just wondering if that yellow headline/definition treatment might be needed on this page too.

**Comment by Tanuja-Sawant** [comment]
@equivalentideas may I take this up?

**Comment by henare** [comment]
@Tanuja-Sawant for sure! :zap: 

The hardest thing to get right in this issue will be the wording. I'd suggest working on that in this issue before opening a pull request. @kat is really good with wording so it's worth asking her to review what you come up with :+1:

**Comment by Tanuja-Sawant** [comment]
@kat, where exactly on the page should I add the context for 'What are edits?',  'How to make edits?' and the call to action to join?
What is a 'section' when you suggested making the call to action to join in the last section?
How would you like the wording to be? Do you have any references so that I can formulate content for the description?
